
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author gabriel.machado4
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtDisciplina = new javax.swing.JTextField();
        cmbCurso = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        optMasc = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        optPT = new javax.swing.JRadioButton();
        optIN = new javax.swing.JRadioButton();
        optES = new javax.swing.JRadioButton();
        optAL = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOBS = new javax.swing.JTextArea();
        btnNovo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTabela = new javax.swing.JTable();
        btnAdcionar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btnAbrirJanela = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SWING 2");
        setMaximizedBounds(getMaximizedBounds());
        setSize(getMaximumSize());
        getContentPane().setLayout(null);

        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(26, 35, 36, 16);

        jLabel2.setText("Curso:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(26, 69, 34, 16);

        jLabel3.setText("Disciplina:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(26, 103, 54, 16);

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome);
        txtNome.setBounds(98, 32, 255, 22);

        txtDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDisciplinaActionPerformed(evt);
            }
        });
        getContentPane().add(txtDisciplina);
        txtDisciplina.setBounds(98, 100, 255, 22);

        cmbCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manutenção e Suporte em informática", "Informática" }));
        cmbCurso.setSelectedIndex(-1);
        getContentPane().add(cmbCurso);
        cmbCurso.setBounds(98, 66, 255, 22);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Sexo"));

        buttonGroup1.add(optMasc);
        optMasc.setText("Masculino");
        optMasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optMascActionPerformed(evt);
            }
        });

        buttonGroup1.add(jCheckBox2);
        jCheckBox2.setText("Feminino");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optMasc)
                    .addComponent(jCheckBox2))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(optMasc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox2)
                .addGap(26, 26, 26))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(371, 14, 160, 101);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Idiomas"));

        optPT.setText("Português");

        optIN.setText("Inglês");

        optES.setText("Espanhol");

        optAL.setText("Alemão");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optPT)
                    .addComponent(optIN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optES)
                    .addComponent(optAL))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optES)
                    .addComponent(optPT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optIN)
                    .addComponent(optAL))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(550, 19, 193, 100);

        jLabel4.setText("Observações");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(26, 167, 67, 16);

        txtOBS.setColumns(20);
        txtOBS.setRows(5);
        jScrollPane1.setViewportView(txtOBS);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(26, 201, 656, 147);

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNovo);
        btnNovo.setBounds(688, 201, 91, 22);

        tblTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Sexo", "Curso", "Disciplína", "Idiomas", "OBS"
            }
        ));
        jScrollPane2.setViewportView(tblTabela);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(26, 354, 656, 317);

        btnAdcionar.setText("Adicionar");
        btnAdcionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdcionarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdcionar);
        btnAdcionar.setBounds(688, 354, 91, 22);

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemover);
        btnRemover.setBounds(688, 382, 91, 22);

        btnAbrirJanela.setText("Abrir Janela");
        btnAbrirJanela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirJanelaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAbrirJanela);
        btnAbrirJanela.setBounds(688, 616, 91, 22);

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar);
        btnLimpar.setBounds(688, 649, 91, 22);

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        getContentPane().add(btnFechar);
        btnFechar.setBounds(348, 683, 82, 22);

        setSize(new java.awt.Dimension(812, 761));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDisciplinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDisciplinaActionPerformed

    private void optMascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optMascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optMascActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        
        buttonGroup1.clearSelection();
        txtNome.setText("");
        txtDisciplina.setText("");
        cmbCurso.setSelectedIndex(-1);
        optAL.setSelected(false);
        optPT.setSelected(false);
        optIN.setSelected(false);
        optES.setSelected(false);
        txtOBS.setText("");
        
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnAdcionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdcionarActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel dfm = (DefaultTableModel) tblTabela.getModel();
        String linha[] = new String[6];
        linha[0] = txtNome.getText();
        linha[1] = (optMasc.isSelected()?"M":"F");
        linha[2] = (String)cmbCurso.getSelectedItem();
        linha[3] = txtDisciplina.getText();
        String linguas = (optPT.isSelected()?"Português,":"-,");
        linguas += (optIN.isSelected()?"Inglês,":"-,");
        linguas += (optES.isSelected()?"Espanhol,":"-,");
        linguas += (optAL.isSelected()?"Alemão,":"-,");
        linha[4] = linguas;
        linha[5] = txtOBS.getText();
        dfm.addRow(linha);
    }//GEN-LAST:event_btnAdcionarActionPerformed

    private void btnAbrirJanelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirJanelaActionPerformed
        // TODO add your handling code here:
        
        new JanelaVazia().setVisible(true);
    }//GEN-LAST:event_btnAbrirJanelaActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel dfm = (DefaultTableModel)tblTabela.getModel();
        int linha = tblTabela.getSelectedRow();
        if(linha == -1){
            JOptionPane.showMessageDialog(this, "Selecione uma linha");
        }else{
            dfm.removeRow(linha);
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        
        
        DefaultTableModel dfm = (DefaultTableModel)tblTabela.getModel();
        int linhas = tblTabela.getRowCount();
        for(int x=0; x<linhas;x++){
            dfm.removeRow(0);
        }
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        // TODO add your handling code here:
        
        System.exit(0);
    }//GEN-LAST:event_btnFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirJanela;
    private javax.swing.JButton btnAdcionar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnRemover;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbCurso;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton optAL;
    private javax.swing.JRadioButton optES;
    private javax.swing.JRadioButton optIN;
    private javax.swing.JCheckBox optMasc;
    private javax.swing.JRadioButton optPT;
    private javax.swing.JTable tblTabela;
    private javax.swing.JTextField txtDisciplina;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextArea txtOBS;
    // End of variables declaration//GEN-END:variables
}
